name: xcube-icosdp
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.10
  # Required
  - numpy
  - pandas
  - xarray
  - xcube
  # Development Dependencies - Tools
  - black
  - isort
  - pytest
  - pytest-cov
  - ruff
  # Development Dependencies - Demos
  - jupyterlab
  - matplotlib

  # Required, but only available via pip
  - pip
  - pip:
      - icoscp_core
